name: eric_pretest_app
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  lottie: ^2.2.0
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true